var names=[
    "Inappropriate Response",
    "Profit Margin",
    "I Blame Your Mother",
    "Just Passing Through",
    "Reformed Nice Guy",
    "Lacking That Small Match Temperament",
    "Unacceptable Behaviour",
    "Shoot Them Later",
    "The Ends Of Invention",
    "Lasting Damage",
    "Displacement Activity",
    "Smile Tolerantly",
    "Serious Callers Only",
    "Now We Try It My Way",
    "Bora Horza Gobuchul",
    "Just Read The Instructions",
    "A Series Of Unlikely Explanations",
    "Sense Amid Madness, Wit Amidst Folly",
    "Contents May Differ",
    "Ultimate Ship The Second",
    "Not Invented Here",
    "Seed Drill",
    "Total Internal Reflection",
    "Gravitas, What Gravitas?",
    "Misophist",
    "The Usual But Etymologically Unsatisfactory",
    "Revisionist",
    "Poke It With A Stick",
    "Ablation",
    "Funny, It Worked Last Time...",
    "Fate Amenable To Change",
    "Cantankerous",
    "You'll Clean That Up Before You Leave",
    "Quietly Confident,",
    "Rapid Random Response Unit",
    "Use Psychology",
    "Lasting Damage II",
    "Just Testing",
    "Of Course I Still Love You",
    "Passing By And Thought I'd Drop In",
    "All Through With This Niceness And Negotiation Stuff",
    "Headcrash",
    "Never Talk To Strangers",
    "Synchronize Your Dogmas",
    "Recent Convert",
    "Killing Time",
    "Absolutely No You-Know-What",
    "Heavy Messing",
    "Xenophobe",
    "Armchair Traveller",
    "Experiencing A Significant Gravitas Shortfall",
    "Credibility Problem",
    "Steely Glint",
    "Zero Credibility",
    "Nuisance Value",
    "Ethics Gradient",
    "Learned Response",
    "No One Knows What The Dead Think",
    "Sweet and Full of Grace",
    "Empiricist",
    "It's My Party And I'll Sing If I Want To",
    "Hand Me The Gun And Ask Me Again",
    "Stranger Here Myself",
    "Qualifier",
    "Space Monster",
    "Well I Was In The Neighbourhood",
    "Germane Riposte",
    "Value Judgement",
    "But Who's Counting?",
    "Minority Report",
    "Unfortunate Conflict Of Evidence",
    "Perfidy",
    "Pride Comes Before A Fall",
    "The Precise Nature Of The Catastrophe",
    "No More Mr Nice Guy",
    "Zoologist",
    "Very Little Gravitas Indeed",
    "Happy Idiot Talk ",
    "I Blame My Mother",
    "Injury Time",
    "Conventional Wisdom",
    "Halation Effect",
    "Subtle Shift In Emphasis",
    "Charming But Irrational",
    "Pressure Drop",
    "T3OU 736",
    "Another Fine Product From The Nonsense Factory",
    "Kiss This Then",
    "Unwitting Accomplice",
    "Full Refund",
    "You Naughty Monsters",
    "Prime Mover",
    "Teething Problems",
    "Arbitrary",
    "Don't Try This At Home",
    "Low Gravitas Warning Signal",
    "T3OU 118",
    "Cargo Cult",
    "Ravished By The Sheer Implausibility Of That Last Statement",
    "Hylozoist",
    "Undesirable Alien",
    "In One Ear",
    "Just the Washing Instruction Chip in Life's Rich Tapestry",
    "Uninvited Guest",
    "Kakistocrat",
    "A Momentary Lapse Of Sanity",
    "Now Look What You've Made Me Do",
    "A Ship With A View",
    "Not Wanted On Voyage",
    "New Toy",
    "I Thought He Was With You",
    "Death and Gravity",
    "Advanced Case Of Chronic Patheticism",
    "Honest Mistake",
    "Thorough But... Unreliable",
    "Me, I'm Counting",
    "Problem Child",
    "Demented But Determined",
    "Excuses And Accusations",
    "Eschatologist (temporary name)",
    "Prosthetic Conscience",
    "Fine Till You Came Along",
    "Little Rascal",
    "Stood Far Back When The Gravitas Was Handed Out",
    "Caconym",
    "Lasting Damage I",
    "Hidden Income",
    "Only Slightly Bent",
    "Xenoglossicist",
    "Pelagian",
    "Determinist",
    "Boo!",
    "Grey Area (aka Meatfucker)",
    "Just Another Victim Of The Ambient Morality",
    "It'll Be Over By Christmas",
    "Limiting Factor",
    "Screw Loose",
    "Questionable Ethics",
    "Zealot",
    "I Blame The Parents",
    "A Fine Disregard for Awkward Facts",
    "Different Tan",
    "I Said, I've Got A Big Stick",
    "Pure Big Mad Boat Man",
    "You'll Thank Me Later",
    "What Is The Answer and Why?",
    "We Haven't Met But You're A Great Fan Of Mine",
    "Anticipation Of A New Lover's Arrival, The",
    "You Call This Clean?",
    "Gravitas Free Zone",
    "Frank Exchange Of Views",
    "Highpoint",
    "Refreshingly Unconcerned With the Vulgar Exigencies of Veracity",
    "God Told Me To Do It",
    "You May Not Be The Coolest Person Here",
    "Lapsed Pacifist",
    "Thank You And Goodnight",
    "Eight Rounds Rapid",
    "Awkward Customer",
    "Lucid Nonsense",
    "Unreliable Witness",
    "Zero Gravitas",
    "Flexible Demeanour",
    "Sacrificial Victim",
    "Lightly Seared On The Reality Grill",
    "Dramatic Exit",
    "No Fixed Abode",
    "Heresiarch",
    "Gunboat Diplomat",
    "Tactical Grace",
    "Sanctioned Parts List",
    "Wisdom Like Silence",
    "Outstanding Contribution to the Historical Process",
    "Charitable View",
    "Someone Else's Problem",
    "Congenital Optimist",
    "Liveware Problem",
    "You Would If You Really Loved Me",
    "T3OU 4",
    "Big Sexy Beast",
    "Kiss My Ass",
    "Irregular Apocalypse",
    "What Are The Civilian Applications?",
    "Transient Atmospheric Phenomenon",
    "Xenocrat",
    "Falling Outside The Normal Moral Constraints",
    "Arrested Development",
    "Nervous Energy",
    "Gravitas... Gravitas... No, Don't Help Me, I'll Get It In A Moment...",
    "Size Isn't Everything",
    "Bodhisattva, OAQS",
    "Limivorous",
    "Trade Surplus",
    "All The Same, I Saw It First",
    "Vulgarian",
    "So Much For Subtlety",
    "Helpless In The Face Of Your Beauty",
    "Mistake Not…",
    "It's Character Forming",
    "Resistance Is Character-Forming",
    "Warm, Considering",
    "Attitude Adjuster",
    "Jaundiced Outlook",
    "Youthful Indiscretion",
    "Reasonable Excuse",
    "Bad For Business",
    "Yawning Angel",
];

// currently uses above preshuffled.
// TODO: Change to use seeded random
// for sorting

// var seed = 1;

// function random() {
//     var x = Math.sin(seed++) * 10000;
//     return x - Math.floor(x);
// }

// function shuffled(list) {

// }

// names = shuffled(names)

names = names.filter(n=>n.length <= 24)

var npui=NeptunesPride.npui,
    np=NeptunesPride.np,
    U=NeptunesPride.universe,
    G=U.galaxy;

Object.values(G.fleets)
.filter(f=>f.puid==G.player_uid)
.sort((a,b)=>a.uid-b.uid)
.filter(f=>{
  // if a fleet has a taken name,
  // remove the name from the name pool
  // and the fleet by returning false
  var npos = names.indexOf(f.n);
  if(npos !== -1) {
    names.splice(npos, 1);
    return false;
  }
  return true;
}).forEach((f,i)=>{
    U.selectedFleet=f;
    var new_name = names[i];
    // var new_name = 'unit' + i;
    if (f.n == new_name) return;
    console.log("rename_fleet", f.uid, i, f.n, new_name);
    np.onRenameFleet({}, new_name);
})




// Object.values(NeptunesPride.universe.galaxy.players).map(p=>'[['+ p.uid + ']]: [[' + NeptunesPride.universe.galaxy.stars[p.huid].n + ']]').join('\n')
